---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
